GET http://127.0.0.1:6699/word/quiz


###
GET https://japanesejump.com:6699/grammar/?keyword=に


###

###
GET https://japanesejump.com:6699/grammar/speak?content=このマラソン大会には、齢を問わず、


###
GET https://japanesejump.com:6699/grammar/speak?content=hello


###
POST https://japanesejump.com:6699/grammar/report_error
Content-Type: application/json

{ 
    "content": "content"
}
###
POST https://japanesejump.com:6699/grammar/analyze
Content-Type: application/json

{ 
    "content": "ここに車を止められるのは、許可をもらっている人（a だけ　b に限り）です。"
}
###
GET http://127.0.0.1:5000/grammar?keyword=なくし

###
GET http://127.0.0.1:5000/grammar/speak?content=ありがとうございます
###
GET http://127.0.0.1:5000/grammar/audio
Content-Type: audio/mpeg
