POST http://127.0.0.1:5000/grammar/report_error
Content-Type: application/json

{ 
    "content": "content"
}

###
POST https://japanesejump.com:6699/grammar/report_error
Content-Type: application/json

{ 
    "content": "content"
}
###
GET http://127.0.0.1:5000/grammar?keyword=hello

###
GET http://127.0.0.1:5000/grammar/speak?content=ありがとうございます

